### ISSUE TITLE
#5 : JAN 17 2021

### ISSUE THREAD

**Issue by siared** [doodlr-studio/clumsy-face#10]
### 샤
- [ ] 웹사이트 비주얼 디벨롭
- [ ] UI Sound 상업적 사용 가능한 프리소스 취합
   [UI Sound](https://www.notion.so/siawork/UI-Sounds-1e21c6b8f7704632ab2c5b12dc2a4e38)
<img width="1408" alt="KakaoTalk_Photo_2021-01-17-19-37-38" src="https://user-images.githubusercontent.com/32317320/104837969-6cc7c880-58fb-11eb-9f75-6d162df17883.png">

**[To-do]**
- UI Sound 아날로그 위주로 선별해서 컴포넌별로 매칭해보기
- 사이트 컨텐츠 작성

### 혬
- [ ] 사운드 테스트
- [ ] SVG 적용 테스트
- [ ] 반응형 테스트 : 모바일 300, 패드 600, 데탑 900

**[To-do]**
- 구조 리팩토링 : 커스텀 컬러 적용, 카테고리 적용 포함
