### ISSUE TITLE
#2 : July 05 2020

### ISSUE THREAD

**Issue by siared** [doodlr-studio/clumsy-face#3]
# Meeting Notes

## App
alpha url
https://alpha.doodlr.studio/

## Concept Ideas
드로잉 컨셉
https://www.abstrakt.design/all-illustrations?abdf3921_page=2

웹 사이트 컨셉
https://www.figma.com/file/qF7kC1n8DYWKdtXSvQ9gSZ/Untitled?node-id=0%3A1
![image](https://user-images.githubusercontent.com/32317320/86533945-b593d300-bf0f-11ea-9e7c-dd5954182675.png)
![image](https://user-images.githubusercontent.com/32317320/86534181-48813d00-bf11-11ea-9002-7930542c4d72.png)
- 전반적으로 레이아웃, 폰트 등의 요소들이 정형화되지 않은 스타일
- 인터랙션 활용해서 비주얼적으로 단순한 UI 구상 : 캔버스 내부에 클릭 이벤트 기술적으로 가능한지 검토 필요

## To-do
@ssoog 
- [x] Avatar development : @aeei 와 좌표값 의논, 'Soboro' 미팅 때 캐릭터 컨셉 다시 전달

@aeei 
- [ ] Canvas click event
- [ ] Canvas object drag

@siared 
- [x] Web site concept draft
